In [1]:
import numpy as np

In [2]:
import pandas as pd

In [6]:
df= pd.read_csv('trending.csv')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15923 entries, 0 to 15922
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   publish_time       15923 non-null  object
 1   channel_id         15923 non-null  object
 2   title              15923 non-null  object
 3   description        15615 non-null  object
 4   thumbnail_url      0 non-null      float64
 5   thumbnail_width    0 non-null      float64
 6   thumbnail_height   0 non-null      float64
 7   channel_name       15923 non-null  object
 8   tags               14190 non-null  object
 9   category_id        15923 non-null  int64
 10  live_status        15923 non-null  object
 11  local_title        15923 non-null  object
 12  local_description  15615 non-null  object
 13  duration           15923 non-null  object
 14  dimension          15923 non-null  object
 15  definition         15923 non-null  object
 16  caption            15923 non-null  bool
 17  license_status     15923 non-null  bool
 18  allowed_region     540 non-null    object
 19  blocked_region     758 non-null    object
 20  view               15915 non-null  float64
 21  like               15707 non-null  float64
 22  dislike            15707 non-null  float64
 23  favorite           15923 non-null  int64
 24  comment            15807 non-null  float64
 25  trending_time      15923 non-null  object
dtypes: bool(2), float64(7), int64(2), object(15)
memory usage: 2.9+ MB

In [9]:
df.describe

<bound method NDFrame.describe of                publish_time                channel_id  \
0      2021-02-05T09:00:34Z  UCEf_Bc-KVd7onSeifS3py9g
1      2021-02-04T15:54:08Z  UCYEa4_MC7OFjcWrO6SO-u8g
2      2021-02-06T03:00:22Z  UCu12RxQjRQyh79YBYvEDkOg
3      2021-02-05T20:26:08Z  UCCuzDCoI3EUOo_nhCj4noSw
4      2021-02-03T23:14:54Z  UC14UlmYlSNiQCBe9Eookf_A
...                     ...                       ...
15918  2021-06-02T10:53:28Z  UCeHGtIr2IJH1yNMTvea1mzA
15919  2021-05-26T17:00:21Z  UCkYTR78_Knz-3S5NTxJfCIw
15920  2021-05-29T12:04:58Z  UCVNvQrRxK4FOo6_zjjtdhTw
15921  2021-05-31T12:30:13Z  UC6GIiaWJxZyKk_CAVa6y54Q
15922  2021-05-26T07:00:13Z  UCo39yGkzqhxQDhCqyXQ8zsA

                                                   title  \
0                            aespa 에스파 'Forever (약속)' MV
1      [FULL] Siapa di Balik Kudeta AHY? | Dua Sisi t...
2         CABRIOLET CHALLENGE: TANTANGAN MENGGODA (7/12)
3                            With Windah Basudara & Hans
4      🤯 LATE COMEBACK DRAMA! | HIGHLIGHTS | Granada ...
...                                                  ...
15918  INFO BMKG PERINGATAN DINI KAMIS, 3 JUNI 2021: ...
15919  Tak Terima Saat Mobilnya Dirampas Paksa, Pelak...
15920         Romantic Echoes feat. Pamungkas - I'm Down
15921  MASTERCHEF INDONESIA - Ada Yang Girang Banget ...
15922  JUDIKA RAMAIKAN TC RANS CILEGON FC DI BALI, AD...

                                             description  thumbnail_url  \
0      aespa's new single "Forever" is out!\nListen a...            NaN
1      Jakarta, https://www.tvonenews.com - Ketua umu...            NaN
2      Road Party Season 2: Cabriolet Challenge\n\nEp...            NaN
3      Join this channel to get access to perks:\nhtt...            NaN
4      With just two minutes to play, Barça looked to...            NaN
...                                                  ...            ...
15918  Badan Meteorologi Klimatologi dan Geofisika (B...            NaN
15919  Jakarta, tvOnenews.com - Dua debt collector at...            NaN
15920  Romantic Echoes feat. Pamungkas - I'm Down\n\n...            NaN
15921  Pesonanya yang tampan membuat Chef Juna kerap ...            NaN
15922  #JudikaDuma #Judika #DumaRiris\n\nFor Business...            NaN

       thumbnail_width  thumbnail_height            channel_name  \
0                  NaN               NaN                  SMTOWN
1                  NaN               NaN  Indonesia Lawyers Club
2                  NaN               NaN                Motomobi
3                  NaN               NaN                      yb
4                  NaN               NaN            FC Barcelona
...                ...               ...                     ...
15918              NaN               NaN         Tribun Jogja TV
15919              NaN               NaN       Investigasi tvOne
15920              NaN               NaN               Pamungkas
15921              NaN               NaN    MasterChef Indonesia
15922              NaN               NaN             Judika Duma

                                                    tags  category_id  ...  \
0                                                    NaN           10  ...
1      ['tvone', 'tv one', 'tvonenews', 'indonesia la...           25  ...
2      ['MotoMobi', 'Mobil', 'motor', 'review', 'indo...            2  ...
3                                                    NaN           20  ...
4      ['FC Barcelona', 'برشلونة،', 'Fútbol', 'FUTBOL...           17  ...
...                                                  ...          ...  ...
15918  ['TRIBUNJOGJA', 'Berita Jogja', 'Seputar jogja...           25  ...
15919  ['talkshow', 'tvone', 'kabar kriminal', 'krimi...           25  ...
15920                                                NaN           10  ...
15921  ['MasterChef Indonesia', 'RCTI', 'Chef Juna', ...           24  ...
15922  ['Keluarga', 'Cemana', 'judika', 'duma', 'kelu...           24  ...

      caption license_status allowed_region blocked_region       view  \
0        True           True            NaN            NaN  7806846.0
1       False           True            NaN            NaN   885038.0
2       False           True            NaN            NaN   889708.0
3       False           True            NaN            NaN  1006854.0
4       False           True            NaN            NaN  6275035.0
...       ...            ...            ...            ...        ...
15918    True           True            NaN            NaN    79125.0
15919   False           True            NaN            NaN   169200.0
15920   False           True            NaN            NaN   116345.0
15921   False           True            NaN            NaN   576753.0
15922   False           True            NaN            NaN   356521.0

           like  dislike  favorite  comment                     trending_time
0      857902.0  24078.0         0  94961.0  2021-02-07 05:46:51.832614+00:00
1        6765.0   1263.0         0   6365.0  2021-02-07 05:46:51.832649+00:00
2       47895.0    532.0         0   8785.0  2021-02-07 05:46:51.832664+00:00
3       91973.0   3967.0         0  12957.0  2021-02-07 05:46:51.832678+00:00
4      218131.0   4289.0         0  12799.0  2021-02-07 05:46:51.832730+00:00
...         ...      ...       ...      ...                               ...
15918     607.0     37.0         0     58.0  2021-06-03 06:02:08.175035+00:00
15919    1598.0     54.0         0   2970.0  2021-06-03 06:02:08.175087+00:00
15920    7586.0     75.0         0    610.0  2021-06-03 06:02:08.175138+00:00
15921   12948.0    243.0         0    904.0  2021-06-03 06:02:08.175186+00:00
15922    4725.0    126.0         0    226.0  2021-06-03 06:02:08.175225+00:00

[15923 rows x 26 columns]>

In [ ]:
subsetting the dataset based on publish date

filtered_df = df.loc[(df['publish_time'] >= '2021-02-01') & (df['publish_time'] < '2021-02-28')].tail(5)
filtered_df

In [ ]:
subsetting the dataset based on trending date

In [15]:
filtered_df = df.loc[(df['trending_time'] >= '2021-05-01') & (df['trending_time'] < '2021-05-31')].head(5)
filtered_df

,publish_time,channel_id,title,description,thumbnail_url,thumbnail_width,thumbnail_height,channel_name,tags,category_id,...,caption,license_status,allowed_region,blocked_region,view,like,dislike,favorite,comment,trending_time
11466,2021-05-10T09:02:33Z,UCEf_Bc-KVd7onSeifS3py9g,NCT DREAM 엔시티 드림 '맛 (Hot Sauce)' MV,"NCT DREAM's 1st album ""Hot Sauce"" is out!\nLis...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,66458438.0,2119917.0,27072.0,0,637269.0,2021-05-14 12:56:08.334495+00:00
11467,2021-05-12T10:39:24Z,UCmxAIW7RDDC88EPk4ry16Kg,Detik-detik Roket Hamas VS Rudal Pencegat Iron...,"TRIBUN-VIDEO.COM - Militan Palestina, Hamas, m...",NaN,NaN,NaN,Tribunnews.com,"['Tribunnews', 'tribun video', 'tribun', 'Roke...",25,...,False,True,NaN,NaN,4300364.0,53060.0,2163.0,0,12192.0,2021-05-14 12:56:08.334525+00:00
11468,2021-05-13T11:23:42Z,UCER4rvDnRBPr_ncYW4UCZjg,Detik-detik Kendaraan Israel Meledak Akibat Se...,"Jakarta, https://www.tvOnenews.com - Puluhan o...",NaN,NaN,NaN,tvOneNews,"['tvone', 'tvonenews', 'tv one', 'tvone live',...",25,...,False,True,NaN,NaN,3404613.0,48430.0,2604.0,0,16357.0,2021-05-14 12:56:08.334542+00:00
11469,2021-05-13T04:29:38Z,UCfx3oPv3cJm2aCJ7UnhKx8A,SUASANA LEBARAN DI KAMPUNG BETI,mohon maaf lahir dan batin ya..\nsemoga kita s...,NaN,NaN,NaN,Arif muhammad,"['arif muhammad', 'mak beti', 'ma beti', 'mama...",23,...,False,True,NaN,NaN,1680755.0,77458.0,2002.0,0,4251.0,2021-05-14 12:56:08.334557+00:00
11470,2021-05-14T04:00:16Z,UCCY_8y1FjtOegxKB4s2bWqw,Bella Poarch - Build a B*tch (Official Music V...,"Stream ""Build a B*tch"": http://bellapoarch.lnk...",NaN,NaN,NaN,Bella Poarch,"['bella poarch', 'bella porch', 'build a bitch...",22,...,False,True,NaN,NaN,9342745.0,1385322.0,20053.0,0,91456.0,2021-05-14 12:56:08.334572+00:00

In [ ]:
subsetting the dataset based on channels

In [18]:
channels =["SMTOWN"]
condition = df["channel_name"].isin(channels)
df[condition]

,publish_time,channel_id,title,description,thumbnail_url,thumbnail_width,thumbnail_height,channel_name,tags,category_id,...,caption,license_status,allowed_region,blocked_region,view,like,dislike,favorite,comment,trending_time
0,2021-02-05T09:00:34Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Forever (약속)' MV,"aespa's new single ""Forever"" is out!\nListen a...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,7806846.0,857902.0,24078.0,0,94961.0,2021-02-07 05:46:51.832614+00:00
18,2021-02-04T09:00:09Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Forever (약속)' MV Teaser,"aespa's new single ""Forever"" is out!\nListen a...",NaN,NaN,NaN,SMTOWN,NaN,10,...,False,True,NaN,NaN,1926293.0,274399.0,6301.0,0,16390.0,2021-02-07 05:46:51.833035+00:00
200,2021-02-05T09:00:34Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Forever (약속)' MV,"aespa's new single ""Forever"" is out!\nListen a...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,8535337.0,880061.0,26084.0,0,97824.0,2021-02-07 12:15:58.377224+00:00
219,2021-02-04T09:00:09Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Forever (약속)' MV Teaser,"aespa's new single ""Forever"" is out!\nListen a...",NaN,NaN,NaN,SMTOWN,NaN,10,...,False,True,NaN,NaN,1936376.0,274844.0,6327.0,0,16403.0,2021-02-07 12:15:58.377496+00:00
402,2021-02-05T09:00:34Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Forever (약속)' MV,"aespa's new single ""Forever"" is out!\nListen a...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,9745275.0,927749.0,29544.0,0,104522.0,2021-02-08 11:56:45.332377+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15095,2021-05-10T09:02:33Z,UCEf_Bc-KVd7onSeifS3py9g,NCT DREAM 엔시티 드림 '맛 (Hot Sauce)' MV,"NCT DREAM's 1st album ""Hot Sauce"" is out!\nLis...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,89983562.0,2719547.0,41099.0,0,1011673.0,2021-05-30 06:01:52.021044+00:00
15197,2021-05-17T09:00:02Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Next Level' MV,"aespa's new single ""Next Level"" is out!\nListe...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,84220551.0,1866783.0,70597.0,0,309222.0,2021-05-31 06:00:54.148685+00:00
15428,2021-05-17T09:00:02Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Next Level' MV,"aespa's new single ""Next Level"" is out!\nListe...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,85069184.0,1879932.0,71199.0,0,311611.0,2021-06-01 06:01:29.286302+00:00
15653,2021-05-17T09:00:02Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Next Level' MV,"aespa's new single ""Next Level"" is out!\nListe...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,85890112.0,1892424.0,71804.0,0,314389.0,2021-06-02 06:00:58.385691+00:00
15877,2021-05-17T09:00:02Z,UCEf_Bc-KVd7onSeifS3py9g,aespa 에스파 'Next Level' MV,"aespa's new single ""Next Level"" is out!\nListe...",NaN,NaN,NaN,SMTOWN,NaN,10,...,True,True,NaN,NaN,86671375.0,1905387.0,72420.0,0,316850.0,2021-06-03 06:02:08.174343+00:00

In [ ]:
grouping based on channels

In [22]:
print(df.groupby(["channel_name"])[['publish_time']].count())

                                             publish_time
channel_name
#temantapimenikah                                       4
(G)I-DLE (여자)아이들 (Official YouTube Channel)             9
1 vs 9999                                              14
10 News First                                          13
100kpj com                                              2
...                                                   ...
최시원 Siwon Choi                                          8
키이스트 KEYEAST official                                   3
피기보이 PiggyBoy                                           1
한밤 HANBAM                                               1
혀니콤보 TV                                                 8

[1143 rows x 1 columns]

In [ ]:
grouping based on trending date

In [42]:
df_parse = pd.read_csv('trending.csv', parse_dates=['trending_time'])
df_parse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15923 entries, 0 to 15922
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   publish_time       15923 non-null  object
 1   channel_id         15923 non-null  object
 2   title              15923 non-null  object
 3   description        15615 non-null  object
 4   thumbnail_url      0 non-null      float64
 5   thumbnail_width    0 non-null      float64
 6   thumbnail_height   0 non-null      float64
 7   channel_name       15923 non-null  object
 8   tags               14190 non-null  object
 9   category_id        15923 non-null  int64
 10  live_status        15923 non-null  object
 11  local_title        15923 non-null  object
 12  local_description  15615 non-null  object
 13  duration           15923 non-null  object
 14  dimension          15923 non-null  object
 15  definition         15923 non-null  object
 16  caption            15923 non-null  bool
 17  license_status     15923 non-null  bool
 18  allowed_region     540 non-null    object
 19  blocked_region     758 non-null    object
 20  view               15915 non-null  float64
 21  like               15707 non-null  float64
 22  dislike            15707 non-null  float64
 23  favorite           15923 non-null  int64
 24  comment            15807 non-null  float64
 25  trending_time      15923 non-null  datetime64[ns, UTC]
dtypes: bool(2), datetime64[ns, UTC](1), float64(7), int64(2), object(14)
memory usage: 2.9+ MB

In [43]:
df_parse.resample('D', on='trending_time').mean()

,thumbnail_url,thumbnail_width,thumbnail_height,category_id,caption,license_status,view,like,dislike,favorite,comment
trending_time,,,,,,,,,,,
2021-02-07 00:00:00+00:00,NaN,NaN,NaN,18.827500,0.137500,0.972500,2.137917e+06,107702.824873,2576.850254,0.0,11927.673522
2021-02-08 00:00:00+00:00,NaN,NaN,NaN,18.380000,0.135000,0.980000,2.224332e+06,113298.822335,2752.162437,0.0,12472.876923
2021-02-09 00:00:00+00:00,NaN,NaN,NaN,18.462500,0.117500,0.955000,2.252526e+06,103218.733503,2834.606599,0.0,11364.979695
2021-02-10 00:00:00+00:00,NaN,NaN,NaN,18.675000,0.120000,0.960000,2.381178e+06,111133.472081,3003.857868,0.0,12201.191919
2021-02-11 00:00:00+00:00,NaN,NaN,NaN,18.361809,0.135678,0.949749,2.261502e+06,100440.456853,2924.949239,0.0,9336.222222
...,...,...,...,...,...,...,...,...,...,...,...
2021-05-30 00:00:00+00:00,NaN,NaN,NaN,17.705000,0.180000,0.955000,6.871297e+06,357630.186869,7266.439394,0.0,65455.530000
2021-05-31 00:00:00+00:00,NaN,NaN,NaN,17.730000,0.155000,0.960000,6.772104e+06,354253.884422,6902.753769,0.0,60495.325000
2021-06-01 00:00:00+00:00,NaN,NaN,NaN,17.425000,0.190000,0.960000,6.600628e+06,352761.530000,6683.715000,0.0,60936.450000
2021-06-02 00:00:00+00:00,NaN,NaN,NaN,17.475000,0.190000,0.945000,5.894141e+06,308302.955000,5345.610000,0.0,51358.905000
2021-06-03 00:00:00+00:00,NaN,NaN,NaN,17.785000,0.185000,0.955000,5.972905e+06,318994.425000,5426.765000,0.0,52884.860000

In [ ]:
number of uniques channels

In [44]:
print(df.nunique())

publish_time          3652
channel_id            1142
title                 3738
description           3575
thumbnail_url            0
thumbnail_width          0
thumbnail_height         0
channel_name          1143
tags                  2654
category_id             15
live_status              1
local_title           3738
local_description     3575
duration              1564
dimension                1
definition               2
caption                  2
license_status           2
allowed_region          31
blocked_region          83
view                 15846
like                 14056
dislike               5041
favorite                 1
comment               8576
trending_time        15923
_id                  15923
dtype: int64

In [45]:
print(df.nunique(axis=1))

0        18
1        19
2        19
3        18
4        19
         ..
15918    19
15919    19
15920    18
15921    19
15922    19
Length: 15923, dtype: int64

In [46]:
print(df['channel_name'].value_counts())

TRANS7 OFFICIAL                165
Deddy Corbuzier                151
SMTOWN                         133
Indonesian Idol                128
KOMPASTV                       127
                              ...
PUBG MOBILE                      1
New Home Items                   1
SBS Entertainment                1
Geraldytan Channel               1
Free Fire Malaysia Official      1
Name: channel_name, Length: 1143, dtype: int64

In [47]:
print(df['tags'].value_counts())

['123', '123 go', '123go', '123 go gold', '123gogold', '123go!', '123 go!', '123 go! gold', '123go!gold', 'tantangan', 'lelucon', 'trik kehidupan', 'DIY', 'kerajinan', 'proyek DIY', 'bermain peran', 'komedi', 'sketsa', 'humor', 'tertawa', 'sketsa komedi', 'trik', 'kerjakan sendiri', 'seru', 'lucu', 'video lucu', 'sketsa lucu', 'video seru', 'langkah-langkah', 'cara membuat', 'tutorial', 'buatan tangan', 'buatan rumah']                                                                                                                                                         116
['BIGHIT', '빅히트', '방탄소년단', 'BTS', 'BANGTAN', '방탄']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              94
['Globaltvseru', 'GTV', 'GlobalTVIndonesia', 'GlobalTV Indonesia', 'Global TV Indonesia', 'Globaltv seru', 'MNC Group', 'The Voice', 'The Voice Kids', 'The Voice Kids Indonesia', 'TVK Indonesia', 'TVKI', 'Television Show', 'TV Program', 'Song Competition', 'Singer', 'The Voice Kids Coach', 'Battles', 'TVKI Season 4', 'Kaka', 'Marcell Siahaan', 'Marcell', 'yura yunita', 'rizky febian']                                                                                                                                                                                             89
['net', 'media', 'netmedia', 'netmediatama', 'indonesia', 'jakarta', 'Wishnutama', 'Agus Lasmono', 'net tv', 'entertainment', 'indika', 'indika energy', 'indika production', 'keren', 'intm', 'deddy corbuzier', "indonesia's next top model", 'patricia gouw', 'pat gow', 'panca makmun', 'luna maya', 'yumi', 'gea']                                                                                                                                                                                                                                                                         88
['방탄소년단', 'BTS', 'BANGTAN', 'HIPHOP', '알엠', 'RM', '슈가', 'SUGA', '제이홉', 'jhope', '지민', 'JIMIN', '정국', 'JUNGKOOK', 'JIN']                                                                                                                                                                                                                                                                                                                                                                                                                                                                         75
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...
['team rrq', 'rrq', 'rex regum qeon', 'viva rrq', 'rrq vyn', 'rrq lemon', 'lemon rrq', 'lemon', 'vyn rrq', 'rrq wizzking', 'wizzking', 'r7', 'r7 tatsumaki', 'rrq xin', 'xin', 'xinnn', 'rrq albert', 'rrq alberttt', 'alberttt', 'rrq psycho', 'rrq psychoo', 'rrq m2', 'mobile legends', 'mlbb indonesia', 'rrq hoshi', 'evos', 'mic check rrq', 'rrq mic check', 'rrq vlog', 'psychoo', 'rrq acil', 'acil', 'RRQ HOSHI', 'rrq taka', 'player baru rrq', 'btr taka', 'xinnn pensiun', 'xinnn rehat', 'mpl', 'mpl s7', 'mpl season 7', 'rrq mpl', 'KEPUTUSAN XINNN', 'XINNN', 'Keputusan']      1
['israel', 'palestine', 'gaza', 'rockets']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
['among us', 'among us cup song', 'among us animation', 'among us memes', 'among us funny', 'among us funny moments', 'among us meme', 'among us iq', 'among us hacks', 'among us impostor', 'among us best players', 'amongamong us 100 iq', 'cup song girl', 'among us mods', 'new cup song girl', 'among us song', 'among us perfect timing', 'worst timing', 'perfect timing', 'cup song', 'impostor', 'funny moments', 'funny', 'cupsong vs girl', 'among us cheats', 'funny among us', 'pumma']                                                                                            1
['yt:cc=on', 'virgoun', 'surat cinta untuk starla', 'bukti', 'scus', 'starla', 'last child', 'selamat selamat tinggal', 'move on', 'caitlin halderman', 'seluruh nafas ini', 'diary depresiku', 'musik', 'music', 'indonesia', 'negeri di awan', 'katon bagaskara', 'virgoun terbaru', 'lagu virgoun', 'lagu baru virgoun', 'negeri di awan lirik', 'negeri di awan cover', 'lagu', 'Virgoun Unplugged', 'negeri di awan katon bagaskara', 'negeri di awan live', 'roman picisan', 'lagu katon bagaskara', 'titik balik di hidupku', 'kla project']                                              1
['viva', 'newstainment', 'news', 'berita', 'viva.co.id', 'vivacoid', 'Masuk Jurang', 'Rem Blong', 'bus pariwisata', 'SMP IT Al Muawanah', 'CCTV', 'kecelakaan', 'Tanjakan', 'RS Sumedang', 'Viral']                                                                                                                                                                                                                                                                                                                                                                                              1
Name: tags, Length: 2654, dtype: int64